### ISSUE TITLE
コードレビュー vv

### ISSUE THREAD

**Issue by vvakame** [asada0701/NoughtsAndCrosses#11]
* NumOfPlayerException は NumberOfPlayerException とかのほうがいいですね
  * InvalidPlayerNumberException とかのほうがそれっぽい気もする
* `do-while文先頭で +1 するので -1 で良い` というコメントが必要なのがダサいので `playerIndex++;` をもっと後のタイミングにすればいいと思った
  * コメントで補足してわかりにくさを回避するのはよい作戦だけど、そもそもコードをわかりやすくする余地があるならそうしてくれって感じ
* `players[playerIndex]` が頻出しているので `Player currentPlayer = players[playerIndex];` みたいな特定の名前を与えてやってもよさそう
* いらないメソッド消そう
  * PlayerChar#create とか
  * Ruleクラスもいらないのか
* finalにできるものはfinalにしてもいいかも(final主義者の場合
  * Board#verticalLength とか

**Comment by asada0701** [comment]
- [ ] NumOfPlayerException は NumberOfPlayerException とかのほうがいいですね
- [ ] do-while文先頭で +1 するので -1 で良い というコメントが必要なのがダサいので playerIndex++; をもっと後のタイミングにすればいいと思った
コメントで補足してわかりにくさを回避するのはよい作戦だけど、そもそもコードをわかりやすくする余地があるならそうしてくれって感じ
- [ ] players[playerIndex] が頻出しているので Player currentPlayer = players[playerIndex]; みたいな特定の名前を与えてやってもよさそう
- [ ] いらないメソッド消そう
PlayerChar#create とか
Ruleクラスもいらないのか
- [ ] finalにできるものはfinalにしてもいいかも(final主義者の場合
Board#verticalLength とか
