### ISSUE TITLE
コードレビュー vv 2nd

### ISSUE THREAD

**Issue by vvakame** [asada0701/NoughtsAndCrosses#14]
#11 前回

* Board と BoardViewer の存在が謎だ…？
  * こういうやり方はJavaだとあまり見ない気がする
  * Board interface と BoardImpl class を作成して体外的にはBoard interface だけ見せるとか…？
* Matchがなんか微妙では…？
  * 独立のクラスになっている必要性がよくわからない
  * checkGameEnd の内容見るとなぜcheckHorizontalなどがboardになるのか謎だ… どういう基準なんだろう
* 例外についてIllegalとInvalidの使い分けが不明だ(Invalidって書いたの俺だけど
* Board#getGameBoard で配列を外部に出してしまっているので呼び出し側から盤面を破壊可能だ

**Comment by asada0701** [comment]
- [ ] Board と BoardViewer の存在が謎だ…？
こういうやり方はJavaだとあまり見ない気がする
Board interface と BoardImpl class を作成して体外的にはBoard interface だけ見せるとか…？
- [ ] Matchがなんか微妙では…？
独立のクラスになっている必要性がよくわからない
checkGameEnd の内容見るとなぜcheckHorizontalなどがboardになるのか謎だ… どういう基準なんだろう
- [ ] 例外についてIllegalとInvalidの使い分けが不明だ(Invalidって書いたの俺だけど
- [ ] Board#getGameBoard で配列を外部に出してしまっているので呼び出し側から盤面を破壊可能だ

**Comment by asada0701** [comment]
illegal と invalid の使い分けはネイティブでも難しそう。
とりあえずillegalで統一。
