### ISSUE TITLE
追加仕様

### ISSUE THREAD

**Issue by laco0416** [asada0701/NoughtsAndCrosses#23]
以下の2つの仕様変更を加えます

- 弱いCPUと強いCPUを選択可能にし好きな方と対戦できるようにせよ
- ○と×の手番が交互ではなくランダムに決まるようにせよ

**Comment by asada0701** [comment]
- [ ] 弱いCPUと強いCPUを選択可能にし好きな方と対戦できるようにせよ
- [ ] ○と×の手番が交互ではなくランダムに決まるようにせよ

**Comment by asada0701** [comment]
* 例外の説明には原因を書く。
 * switch文のdefaultは自作例外でなくても良いが、RuntimeExceptionを使うと本当にRuntimeExceptionを使いたい時に困るので、
 * defaultに入ったという例外を作った方が良い。

**Comment by asada0701** [comment]
抽象クラスは渡したものを使わないことはよくある。その実装では使わなかったというだけ
