### ISSUE TITLE
コードレビュー vv 2nd

### ISSUE THREAD

**Issue by vvakame** [asada0701/NoughtsAndCrosses#29]
* BoardFactory#create について
  * 返り値の型が BoardImpl なのはよくない(Implはインタフェースではない、隠蔽されるべき型のはず
* 結局 `int[][]` を返すメソッドはなくなったのかしら？
  * 考えたうえでそうしたならOKだけどよくわからなかったので逃げた だとやだなー
  * どうかしら？
* BoardImpl#checkUpperLeftToLowerRight が abstract になっているのはどういう狙いの抽象化なんだろうか？
  * ぱっとみいらんのとちゃうか？みたいな気持ちになる
  * SquareBoard で checkGameEnd をOverride すればいいのでは
* CuiTest がちゃんと書けてて偉い
* 不要なインスタンス変数を減らそう
  * CpuLevelTest の `CpuLevel sut` とか
  * 状態をメソッド間で共有しないならインスタンス変数じゃなくてよいはず
  * 独立したテストであることが示されていたほうが良い

**Comment by asada0701** [comment]
- [ ] BoardFactory#create について
返り値の型が BoardImpl なのはよくない(Implはインタフェースではない、隠蔽されるべき型のはず
- [ ] 結局 int[][] を返すメソッドはなくなったのかしら？
考えたうえでそうしたならOKだけどよくわからなかったので逃げた だとやだなー
どうかしら？
- [ ] BoardImpl#checkUpperLeftToLowerRight が abstract になっているのはどういう狙いの抽象化なんだろうか？
ぱっとみいらんのとちゃうか？みたいな気持ちになる
SquareBoard で checkGameEnd をOverride すればいいのでは
- [ ] 不要なインスタンス変数を減らそう
CpuLevelTest の CpuLevel sut とか
状態をメソッド間で共有しないならインスタンス変数じゃなくてよいはず
独立したテストであることが示されていたほうが良い

**Comment by asada0701** [comment]
Board#copyGameBoard
は名前が微妙
BoardがgameBoardという変数を持つのが原因。
しかし、命名が難しいので、このままでも良い。

**Comment by asada0701** [comment]
BoardImplの隠蔽について
Boardのパッケージをなくしてしまって、アクセス修飾子で対応すればよい。
