### ISSUE TITLE
コードレビュー laco

### ISSUE THREAD

**Issue by laco0416** [asada0701/NoughtsAndCrosses#9]
ざっくりいい気はする ところどころ冗長だけどまあ良いレベル 

## PlayerがBoardにアクセスできる問題

PlayerクラスがBoardをコンストラクタで受け取っているので、selectメソッドでintを返さなくても、自分でthis.boardをいじって任意の盤面にすることができる。ルール破壊。
それが可能な設計なんです！ということならそれでもいいけど、普通はそれが出来ないような制約を与えておきたい気がする。

## PlayerChar周り

メソッドに隠蔽してるけど、`getNoughts()` とか実質 `◯` 指定しているのとあまり変わらんのでは？
Playerがnewされたときに自分自身の文字を得るほうが自然だと思うので、そもそもMainから触るものじゃない気がするし、 `PlayerChar.getNext()` とかで呼び出すたびに違う文字が得られる(上限はあるだろうけど)ような設計のほうが良い気がする

**Comment by asada0701** [comment]
- [ ] PlayerがBoardにアクセスできる問題
- [ ] PlayerChar周り

**Comment by laco0416** [comment]
だいたい良い気がする 

## BoardFactory

- 未実装だからreturn nullしているんだろうけど、そういうときは例外を投げたほうがいい。前にも言ったけどnullにnullである以上の意味を持たせてメッセージングに使ってはいけない。到達してはいけない場所に処理が来たなら例外を発生させるほうがいい

## Player

- コンストラクタは初期値を与えて初期化を行うためのものだけど、BoardViewerは初期化に必要なんだろうか。selectで毎回その時点の盤面が入力として与えられて、それに対する指し手を出力とするメソッドのほうが、テストもしやすそうに思うけどどうだろうか

## BoardViewer

- テスト用に `getBoard()` を用意してるけど使われてないし、現実問題としてgetBoardがあったらアプリケーションから使われることを防げないので、そういうメソッドが必要なんだったらテスタビリティが低い設計になっているということだと思うぞ！

CPUPlayerでもselectで返ってくる値が配置可能な数字であるかどうかのテストくらいはできるだろうという気がする。
CuiTestも、特定のboardの状態がちゃんと格子状に期待通りの描画をされるかのテストは必要だと思われる

**Comment by asada0701** [comment]
- [ ] BoardFactory
未実装だからreturn nullしているんだろうけど、そういうときは例外を投げたほうがいい。前にも言ったけどnullにnullである以上の意味を持たせてメッセージングに使ってはいけない。到達してはいけない場所に処理が来たなら例外を発生させるほうがいい
- [ ] Player
コンストラクタは初期値を与えて初期化を行うためのものだけど、BoardViewerは初期化に必要なんだろうか。selectで毎回その時点の盤面が入力として与えられて、それに対する指し手を出力とするメソッドのほうが、テストもしやすそうに思うけどどうだろうか
- [ ] BoardViewer
テスト用に getBoard() を用意してるけど使われてないし、現実問題としてgetBoardがあったらアプリケーションから使われることを防げないので、そういうメソッドが必要なんだったらテスタビリティが低い設計になっているということだと思うぞ！

**Comment by asada0701** [comment]
クラス定義に基づいて生成されるのがインスタンス。
コンストラクタとは、このインスタンスを生成するための専用構文。
BoardViewerの場合は中身があれこれ変わるのでプレイヤーの持ち物ではない

**Comment by laco0416** [comment]
# Board

- `int board.getGameBoard(i, k)` って名前おかしくないだろうか 取得しているのはBoardじゃなくてひとつのマスの状態では？もっというと現在のそのマスの持ち主のIDが返ってくるんだからそういう名前にしないといけないだろう

# HumanPlayer

これはatozeにも言ったが、Cui以外の場所にCuiの都合が出てきたらもうCui作った意味がない。selectForCuiというメソッドがHumanPlayerにある時点でCui以外で使えなくなってる
人間に対するメッセージの表示や、入力の受取を抽象化するためのCuiであるはずなので見直して欲しい。HumanPlayerはSystem.inから入力を受け取るのではなくUiから入力を受け取る、というレベルに抽象化しないと意味ない

**Comment by asada0701** [comment]
- [ ] HumanPlayerはSystem.inから入力を受け取るのではなくUiから入力を受け取る、というレベルに抽象化しないと意味ない
